### ISSUE TITLE
Setup pre commit hook using husky

### ISSUE THREAD

**Issue by abhimishra01** [javascript-shinobis/nike-clone-app#14]
#### we need a pre commit that does the following :-
- auto prettifies the staged files
- check eslint errors

#### Note :- unit tests are out of scope for now, in future we are gonna have it in this pre commit hook

**Comment by KaustubhTrivedi** [comment]
Okay will do

**Comment by abhimishra01** [comment]
> @abhimishra01 is this issue still open to work?

@vdwaseem , this is a small issue and @KaustubhTrivedi has already been assigned to work on the same, 
we do have some more issues coming up soon, we will surely mention you in one of those

**Comment by abhimishra01** [comment]
> > @abhimishra01 is this issue still open to work?
> 
> @vdwaseem , this is a small issue and @KaustubhTrivedi has already been assigned to work on the same, we do have some more issues coming up soon, we will surely mention you in one of those

I believe you have already raised [one ](https://github.com/javascript-shinobis/nike-clone-app/issues/17#issue-1767789198)
cool
