### ISSUE TITLE
Github Issue Template

### ISSUE THREAD

**Issue by abhimishra01** [javascript-shinobis/nike-clone-app#18]
- we have been getting frequent issues raised on our repository
- it would be nice to have a standard `ISSUE TEMPLATE` which has some set of todos, checklist, notes, etc to point out what exactly is happening or what needs to be done / fixed
- open to assign this to someone new, else someone from active maintainer will pick this up in next 2 days

**Comment by Uzafar90** [comment]
Hey @abhimishra01
Just for clarification, Are you requesting to create the Github "Issue Template" in your project?

**Comment by abhimishra01** [comment]
> Hey @abhimishra01
> Just for clarification, Are you requesting to create a custom Github "Issue Template" for your repository? 

Yeah, we've just started with the project, so if someone is interested they can, else we will pick it up :)

**Comment by Uzafar90** [comment]
I'm currently at work but I'll go ahead and fork it so I can work on it tonight.

**Comment by Uzafar90** [comment]
@abhimishra01 You can assign it to me.

**Comment by Uzafar90** [comment]
@abhimishra01  I see that you already have a .github file in your project. Do you want me to edit that or create a new one?

**Comment by abhimishra01** [comment]
> @abhimishra01  I see that you already have a .github file in your project. Do you want me to edit that or create a new one?

Yes, append the file inside the .GitHub folder

**Comment by Uzafar90** [comment]
@abhimishra01  I have created the files you requested, please check it out and let me know if any changes need to be made.

**Comment by abhimishra01** [comment]
> @abhimishra01 I have created the files you requested, please check it out and let me know if any changes need to be made.

Dammn man, thanks for the contribution, your issue template seems working fantastically

**Comment by Uzafar90** [comment]
I'm happy to hear that you appreciate my contribution. Hopefully, the process of creating issues in the future will be more peaceful.

**Comment by abhimishra01** [comment]
> I'm happy to hear that you appreciate my contribution. Hopefully, the process of creating issues in the future will be more peaceful.

haha, yes, it surely will🚀
