### ISSUE TITLE
Configure tailwind CSS & Eslint

### ISSUE THREAD

**Issue by abhimishra01** [javascript-shinobis/nike-clone-app#7]
- configure tailwind css & eslint
- install necessary dependencies listed in the video

**Comment by KaustubhTrivedi** [comment]
Can you assign this to me as well? I can do it.

**Comment by abhimishra01** [comment]
> Can you assign this to me as well? I can do it.

Sure man, 
But i am afraid this issue is kinda a small task in itself and i believe @bhanu0187 is already on it.

We have just started on the project though and just started creating tasks and issues.
Shall I assign some other issue to you, if you are interested?

**Comment by KaustubhTrivedi** [comment]
Yes will do you can

**Comment by bhanu0187** [comment]
@KaustubhTrivedi we have raised a new [issue](https://github.com/javascript-shinobis/nike-clone-app/issues/14) you can work on this.
